### ISSUE TITLE
"File does not exist at path .env."

### ISSUE THREAD

**Issue by Ant-V** [syamsoul/laravel-set-env#3]
When trying to call: `$envService = new Env();` from any place I could think of, I get the following `Illuminate\Contracts\Filesystem\FileNotFoundException`: `File does not exist at path .env.`

Since the artisan command works perfectly, I think it might have something to do with the file drivers, for which I have the default configs.

**Comment by syamsoul** [comment]
> When trying to call: `$envService = new Env();` from any place I could think of, I get the following `Illuminate\Contracts\Filesystem\FileNotFoundException`: `File does not exist at path .env.`
> 
> Since the artisan command works perfectly, I think it might have something to do with the file drivers, for which I have the default configs.

we will fix this in next release... thanks for open this issue...

**Comment by syamsoul** [comment]
@Ant-V issue resolved in [1.0.6](https://github.com/syamsoul/laravel-set-env/releases/tag/1.0.6)

**Comment by midblep** [comment]
This issue is still present in 1.0.6 for me. Just like the initial report, using it with Artisan works fine.

**Comment by syamsoul** [comment]
> This issue is still present in 1.0.6 for me. Just like the initial report, using it with Artisan works fine.

Sorry @Ant-V and @midblep , my mistake in releasing the version. Now the fix should be in version [1.0.7](https://github.com/syamsoul/laravel-set-env/releases/tag/1.0.7)
